! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : r2smh_Rates.f90
! Time                 : Fri Mar 11 14:25:20 2016
! Working directory    : /global/scratch/azare/Josh/WRFV3/chem/KPP/mechanisms/r2smh
! Equation file        : r2smh.kpp
! Output root filename : r2smh
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE r2smh_Rates

  USE r2smh_Parameters
  USE r2smh_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL,     INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL,     INTENT(IN) :: n         ! exponent for low pressure limit
    REAL,     INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL,     INTENT(IN) :: m         ! exponent for high pressure limit
    REAL,     INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL                 :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


REAL(KIND=dp) FUNCTION k46( TEMP, C_M )
    REAL(KIND=dp), INTENT(IN) :: temp, c_m
    REAL(KIND=dp) :: k0, k2, k3 

   k0=2.4E-14_dp * EXP(460._dp/TEMP)
   k2=2.7E-17_dp * EXP(2199._dp/TEMP)
   k3=6.5E-34_dp * EXP(1335._dp/TEMP) * C_M

   k46=k0+k3/(1+k3/k2)


END FUNCTION k46

REAL(KIND=dp) FUNCTION ko1d(TEMP, C_M)
    REAL(KIND=dp), INTENT(IN) :: temp, c_m
    REAL(KIND=dp) :: kN, kO
    kN = 0.78084_dp * C_M * 1.8E-11_dp * EXP(107._dp/TEMP)
    kO = 0.20946_dp * C_M * 3.2E-11_dp * EXP(67._dp/TEMP)
    ko1d=kN+kO
END FUNCTION ko1d

! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE r2smh_Parameters
      !USE r2smh_Global

    IMPLICIT NONE

    REAL(kind=dp) SunRise, SunSet
    REAL(kind=dp) Thour, Tlocal, Ttmp 
   
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (j(Pj_o33p))
  RCONST(2) = (j(Pj_o31d))
  RCONST(3) = (j(Pj_h2o2))
  RCONST(4) = (j(Pj_no2))
  RCONST(5) = (j(Pj_no3o2))
  RCONST(6) = (j(Pj_no3o))
  RCONST(7) = (j(Pj_hno2))
  RCONST(8) = (j(Pj_hno3))
  RCONST(9) = (j(Pj_hno4))
  RCONST(10) = (j(Pj_ch2om))
  RCONST(11) = (j(Pj_ch2or))
  RCONST(12) = (j(Pj_ch3cho))
  RCONST(13) = (j(Pj_ald))
  RCONST(14) = (j(Pj_ch3coch3))
  RCONST(15) = (j(Pj_uald))
  RCONST(16) = (j(Pj_ch3coc2h5))
  RCONST(17) = (j(Pj_ch3coc2h5))
  RCONST(18) = (j(Pj_ch3coc2h5))
  RCONST(19) = (j(Pj_macr))
  RCONST(20) = (j(Pj_mvk))
  RCONST(21) = (j(Pj_hcocho))
  RCONST(22) = (j(Pj_hcochob))
  RCONST(23) = (j(Pj_hcochoc))
  RCONST(24) = (j(Pj_ch3cocho))
  RCONST(25) = (j(Pj_ch3cocho))
  RCONST(26) = (j(Pj_ch3cocho))
  RCONST(27) = (j(Pj_bald))
  RCONST(28) = (j(Pj_ch3o2h))
  RCONST(29) = (j(Pj_ch3o2h))
  RCONST(30) = (j(Pj_ch3coo2h))
  RCONST(31) = (j(Pj_iprno3))
  RCONST(32) = (j(Pj_pana))
  RCONST(33) = (j(Pj_panb))
  RCONST(34) = (ARR2(1.70D-12,940.0_dp,TEMP))
  RCONST(35) = (ARR2(1.00D-14,490.0_dp,TEMP))
  RCONST(36) = (ARR2(1.40D-12,1310.0_dp,TEMP))
  RCONST(37) = (ARR2(1.40D-13,2470.0_dp,TEMP))
  RCONST(38) = ((.20946*C_M*5.74D-34*(TEMP/300.0_dp)**(-2.6)))
  RCONST(39) = (ARR2(8.00D-12,2060.0_dp,TEMP))
  RCONST(40) = (ko1d(TEMP,C_M))
  RCONST(41) = (2.20D-10)
  RCONST(42) = ((5.31D-7*ARR2(7.70D-12,2100.0_dp,TEMP)))
  RCONST(43) = (ARR2(4.80D-11,-250.0_dp,TEMP))
  RCONST(44) = ((2.2D-13*EXP(600./TEMP)+1.90D-33*C_M*EXP(980./TEMP)))
  RCONST(45) = ((3.08D-34*EXP(2800./TEMP)+2.59D-54*C_M*EXP(3180./TEMP)))
  RCONST(46) = (ARR2(2.90D-12,160.0_dp,TEMP))
  RCONST(47) = (TROE(9.00D-32,1.5_dp,3.00D-11,0.0_dp,TEMP,C_M))
  RCONST(48) = (TROE(7.00D-31,2.6_dp,3.60D-11,0.1_dp,TEMP,C_M))
  RCONST(49) = (ARR2(3.60D-12,-270.0_dp,TEMP))
  RCONST(50) = ((.20946*ARR2(3.30D-39,-530.0_dp,TEMP)))
  RCONST(51) = (ARR2(2.50D-12,-260.0_dp,TEMP))
  RCONST(52) = (ARR2(5.50D-12,-188.0_dp,TEMP))
  RCONST(53) = (TROE(2.50D-31,1.8_dp,2.20D-11,0.7_dp,TEMP,C_M))
  RCONST(54) = (TROE(1.49D-30,1.8_dp,2.58D-11,0.0_dp,TEMP,C_M))
  RCONST(55) = (k46(TEMP,C_M))
  RCONST(56) = (2.00D-11)
  RCONST(57) = (4.00D-12)
  RCONST(58) = (ARR2(1.80D-11,-110.0_dp,TEMP))
  RCONST(59) = (ARR2(4.50D-14,1260.0_dp,TEMP))
  RCONST(60) = (ARR2(8.50D-13,2450.0_dp,TEMP))
  RCONST(61) = (TROE(2.00D-30,4.4_dp,1.40D-12,0.7_dp,TEMP,C_M))
  RCONST(62) = (TROEE(3.70D26,11000.0_dp,2.00D-30,4.4_dp,1.40D-12,0.7_dp,TEMP,C_M))
  RCONST(63) = (2.50D-22)
  RCONST(64) = (TROE(2.00D-31,3.4_dp,2.90D-12,1.1_dp,TEMP,C_M))
  RCONST(65) = (TROEE(4.76D26,10900.0_dp,2.00D-31,3.4_dp,2.90D-12,1.1_dp,TEMP,C_M))
  RCONST(66) = (ARR2(1.30D-12,-380.0_dp,TEMP))
  RCONST(67) = (TROE(3.30D-31,4.3_dp,1.60D-12,0.0_dp,TEMP,C_M))
  RCONST(68) = (1.44D-13*(1.0_dp+1.86D-20*C_M))
  RCONST(69) = (ARR2(1.85D-12,1690.0_dp,TEMP))
  RCONST(70) = (ARR2(6.90D-12,1000.0_dp,TEMP))
  RCONST(71) = (ARR2(7.68D-12,370.0_dp,TEMP))
  RCONST(72) = (ARR2(1.01D-11,245.0_dp,TEMP))
  RCONST(73) = (ARR2(2.82D-11,273.0_dp,TEMP))
  RCONST(74) = (TROE(1.00D-28,4.5_dp,8.80D-12,0.85_dp,TEMP,C_M))
  RCONST(75) = (ARR2(5.72D-12,-500.0_dp,TEMP))
  RCONST(76) = (ARR2(1.33D-11,-500.0_dp,TEMP))
  RCONST(77) = (ARR2(1.48D-11,-448.0_dp,TEMP))
  RCONST(78) = (TROE(5.50D-30,0.0_dp,8.30D-13,-2.0_dp,TEMP,C_M))
  RCONST(79) = (ARR2(2.33D-12,193.0_dp,TEMP))
  RCONST(80) = (ARR2(1.81D-12,-354.0_dp,TEMP))
  RCONST(81) = (2.13D-11)
  RCONST(82) = (1.37D-11)
  RCONST(83) = (ARR2(3.1D-11,-350.0_dp,TEMP))
  RCONST(84) = (ARR2(1.21D-11,-440.0_dp,TEMP))
  RCONST(85) = (ARR2(4.20D-11,-401.0_dp,TEMP))
  RCONST(86) = (ARR2(5.50D-12,-125.0_dp,TEMP))
  RCONST(87) = (ARR2(4.38D-12,-366.0_dp,TEMP))
  RCONST(88) = (ARR2(5.10D-12,-405.0_dp,TEMP))
  RCONST(89) = ((8.8D-12*EXP(-1320.0_dp/TEMP)+1.7D-14*EXP(423.0_dp/TEMP)))
  RCONST(90) = (ARR2(1.30D-12,25.0_dp,TEMP))
  RCONST(91) = (ARR2(2.80D-12,-10.0_dp,TEMP))
  RCONST(92) = (3.00D-12)
  RCONST(93) = (ARR2(8.0D-12,-380.0_dp,TEMP))
  RCONST(94) = (ARR2(2.60D-12,-610.0_dp,TEMP))
  RCONST(95) = (ARR2(5.77D-12,-533.0_dp,TEMP))
  RCONST(96) = (1.10D-11)
  RCONST(97) = (ARR2(9.26D-13,-830.0_dp,TEMP))
  RCONST(98) = (ARR2(2.8D-11,-175.0_dp,TEMP))
  RCONST(99) = (ARR2(2.8D-11,-175.0_dp,TEMP))
  RCONST(100) = (1.00D-11)
  RCONST(101) = (ARR2(5.32D-12,-243.0_dp,TEMP))
  RCONST(102) = (ARR2(6.75D-12,-405.0_dp,TEMP))
  RCONST(103) = (4.65D-11)
  RCONST(104) = (ARR2(2.8D-11,-175.0_dp,TEMP))
  RCONST(105) = (2.05D-10)
  RCONST(106) = (ARR2(2.85D-12,345.0_dp,TEMP))
  RCONST(107) = (ARR2(3.00D-12,-20.0_dp,TEMP))
  RCONST(108) = (ARR2(2.60D-12,200.0_dp,TEMP))
  RCONST(109) = (1.47D-11)
  RCONST(110) = (ARR2(2.90D-12,-190.0_dp,TEMP))
  RCONST(111) = (ARR2(3.40D-12,-190.0_dp,TEMP))
  RCONST(112) = (ARR2(1.7D-11,-390.0_dp,TEMP))
  RCONST(113) = (1.66D-11)
  RCONST(114) = (4.50D-13)
  RCONST(115) = (ARR2(2.20D-14,-1012.0_dp,TEMP))
  RCONST(116) = (ARR2(2.93D-12,-190.0_dp,TEMP))
  RCONST(117) = (4.00D-14)
  RCONST(118) = (4.00D-14)
  RCONST(119) = (3.20D-11)
  RCONST(120) = (ARR2(5.31D-12,260.0_dp,TEMP))
  RCONST(121) = (TROE(9.0D-28,8.9_dp,7.7D-12,0.2_dp,TEMP,C_M))
  RCONST(122) = (2.30D-12)
  RCONST(123) = (ARR2(9.14D-15,2580.0_dp,TEMP))
  RCONST(124) = (ARR2(4.33D-15,1800.0_dp,TEMP))
  RCONST(125) = (ARR2(4.40D-15,845.0_dp,TEMP))
  RCONST(126) = (ARR2(1.34D-14,2283.0_dp,TEMP))
  RCONST(127) = (ARR2(7.86D-15,1913.0_dp,TEMP))
  RCONST(128) = (ARR2(5.00D-16,530.0_dp,TEMP))
  RCONST(129) = (ARR2(2.95D-15,783.0_dp,TEMP))
  RCONST(130) = (ARR2(1.4D-15,2100.0_dp,TEMP))
  RCONST(131) = (ARR2(8.5D-16,1520.0_dp,TEMP))
  RCONST(132) = (1.66D-18)
  RCONST(133) = (2.0D-16)
  RCONST(134) = (2.0D-16)
  RCONST(135) = (9.0D-17)
  RCONST(136) = (5.0D-16)
  RCONST(137) = (2.86D-13)
  RCONST(138) = ((THERMAL_T2(4.88D-18,2282.0_dp,TEMP)))
  RCONST(139) = (ARR2(1.79D-13,450.0_dp,TEMP))
  RCONST(140) = (ARR2(8.64D-13,-450.0_dp,TEMP))
  RCONST(141) = (1.00D-13)
  RCONST(142) = (ARR2(3.15D-12,450.0_dp,TEMP))
  RCONST(143) = (ARR2(1.2D-12,-490.0_dp,TEMP))
  RCONST(144) = (1.22D-11)
  RCONST(145) = (ARR2(2.00D-12,2440.0_dp,TEMP))
  RCONST(146) = (ARR2(1.40D-12,1900.0_dp,TEMP))
  RCONST(147) = (ARR2(3.76D-12,1900.0_dp,TEMP))
  RCONST(148) = (3.4D-15)
  RCONST(149) = (ARR2(5.02D-13,1076.0_dp,TEMP))
  RCONST(150) = (ARR2(2.90D-12,1900.0_dp,TEMP))
  RCONST(151) = (ARR2(3.76D-12,1900.0_dp,TEMP))
  RCONST(152) = (3.78D-12)
  RCONST(153) = (1.06D-12)
  RCONST(154) = (ARR2(2.87D-13,1000.0_dp,TEMP))
  RCONST(155) = (2.01D-10)
  RCONST(156) = (ARR2(2.20D-14,500.0_dp,TEMP))
  RCONST(157) = (1.00D3)
  RCONST(158) = (1.00D3)
  RCONST(159) = (1.00D3)
  RCONST(160) = (1.00D3)
  RCONST(161) = (1.00D3)
  RCONST(162) = (1.00D3)
  RCONST(163) = (TROE(9.70D-29,5.6_dp,9.30D-12,1.5_dp,TEMP,C_M))
  RCONST(164) = (TROEE(1.11D28,14000.0_dp,9.70D-29,5.6_dp,9.30D-12,1.5_dp,TEMP,C_M))
  RCONST(165) = (TROE(9.70D-29,5.6_dp,9.30D-12,1.5_dp,TEMP,C_M))
  RCONST(166) = (TROEE(1.11D28,14000.0_dp,9.70D-29,5.6_dp,9.30D-12,1.5_dp,TEMP,C_M))
  RCONST(167) = (TROE(9.0D-28,8.9_dp,7.7D-12,0.2_dp,TEMP,C_M))
  RCONST(168) = (TROEE(1.11D28,14000.0_dp,9.0D-28,8.9_dp,7.7D-12,0.2_dp,TEMP,C_M))
  RCONST(169) = (ARR2(2.80D-12,-300.0_dp,TEMP))
  RCONST(170) = (ARR2(2.60D-12,-365.0_dp,TEMP))
  RCONST(171) = (4.00D-12)
  RCONST(172) = (4.00D-12)
  RCONST(173) = (4.00D-12)
  RCONST(174) = (9.00D-12)
  RCONST(175) = (4.00D-12)
  RCONST(176) = (4.00D-12)
  RCONST(177) = (ARR2(2.54D-12,-360.0_dp,TEMP))
  RCONST(178) = (4.00D-12)
  RCONST(179) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(180) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(181) = (4.00D-12)
  RCONST(182) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(183) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(184) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(185) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(186) = (4.00D-12)
  RCONST(187) = (4.00D-12)
  RCONST(188) = (ARR2(8.10D-12,-270.0_dp,TEMP))
  RCONST(189) = (ARR2(8.10D-12,-270.0_dp,TEMP))
  RCONST(190) = (ARR2(2.90D-12,-300.0_dp,TEMP))
  RCONST(191) = (4.00D-12)
  RCONST(192) = (4.00D-12)
  RCONST(193) = (ARR2(7.5D-12,-290.0_dp,TEMP))
  RCONST(194) = (ARR2(2.7D-12,-350.0_dp,TEMP))
  RCONST(195) = (ARR2(2.54D-12,-360.0_dp,TEMP))
  RCONST(196) = (4.00D-12)
  RCONST(197) = (4.00D-12)
  RCONST(198) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(199) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(200) = (4.00D-12)
  RCONST(201) = (4.00D-12)
  RCONST(202) = (4.00D-12)
  RCONST(203) = (ARR2(2.70D-12,-360.0_dp,TEMP))
  RCONST(204) = (4.00D-12)
  RCONST(205) = (2.00D-11)
  RCONST(206) = (2.00D-11)
  RCONST(207) = (2.08D-12)
  RCONST(208) = (ARR2(4.10D-13,-750.0_dp,TEMP))
  RCONST(209) = (ARR2(7.50D-13,-700.0_dp,TEMP))
  RCONST(210) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(211) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(212) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(213) = (ARR2(1.90D-13,-1300.0_dp,TEMP))
  RCONST(214) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(215) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(216) = (ARR2(2.91D-13,-1300.0_dp,TEMP))
  RCONST(217) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(218) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(219) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(220) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(221) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(222) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(223) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(224) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(225) = (1.50D-11)
  RCONST(226) = (1.50D-11)
  RCONST(227) = (ARR2(4.3D-13,-1040.0_dp,TEMP))
  RCONST(228) = (ARR2(4.3D-13,-1040.0_dp,TEMP))
  RCONST(229) = (ARR2(1.15D-13,-1300.0_dp,TEMP))
  RCONST(230) = (ARR2(1.15D-13,-1300.0_dp,TEMP))
  RCONST(231) = (ARR2(1.15D-13,-1300.0_dp,TEMP))
  RCONST(232) = (ARR2(5.2D-13,-980.0_dp,TEMP))
  RCONST(233) = (ARR2(1.82D-13,-1300.0_dp,TEMP))
  RCONST(234) = (ARR2(2.91D-13,-1300.0_dp,TEMP))
  RCONST(235) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(236) = (1.00D-11)
  RCONST(237) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(238) = (ARR2(1.15D-13,-1300.0_dp,TEMP))
  RCONST(239) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(240) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(241) = (ARR2(3.75D-13,-980.0_dp,TEMP))
  RCONST(242) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(243) = (ARR2(9.50D-14,-390.0_dp,TEMP))
  RCONST(244) = (ARR2(1.18D-13,-158.0_dp,TEMP))
  RCONST(245) = (ARR2(9.46D-14,-431.0_dp,TEMP))
  RCONST(246) = (ARR2(1.00D-13,-467.0_dp,TEMP))
  RCONST(247) = (ARR2(4.34D-14,-633.0_dp,TEMP))
  RCONST(248) = (ARR2(1.71D-13,-708.0_dp,TEMP))
  RCONST(249) = (ARR2(1.46D-13,-708.0_dp,TEMP))
  RCONST(250) = (ARR2(9.18D-14,-708.0_dp,TEMP))
  RCONST(251) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(252) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(253) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(254) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(255) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(256) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(257) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(258) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(259) = (ARR2(3.40D-14,-221.0_dp,TEMP))
  RCONST(260) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(261) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(262) = (ARR2(2.0D-11,-500.0_dp,TEMP))
  RCONST(263) = (ARR2(2.0D-11,-500.0_dp,TEMP))
  RCONST(264) = (ARR2(7.50D-13,-500.0_dp,TEMP))
  RCONST(265) = (ARR2(6.91D-13,-508.0_dp,TEMP))
  RCONST(266) = (ARR2(6.91D-13,-508.0_dp,TEMP))
  RCONST(267) = (ARR2(2.0D-12,-500.0_dp,TEMP))
  RCONST(268) = (1.38D-12)
  RCONST(269) = (ARR2(3.40D-14,-221.0_dp,TEMP))
  RCONST(270) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(271) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(272) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(273) = (ARR2(3.56D-14,-708.0_dp,TEMP))
  RCONST(274) = (ARR2(7.50D-13,-500.0_dp,TEMP))
  RCONST(275) = (ARR2(1.60D-13,-708.0_dp,TEMP))
  RCONST(276) = (ARR2(9.68D-14,-708.0_dp,TEMP))
  RCONST(277) = (3.56D-14)
  RCONST(278) = (ARR2(5.99D-15,-1510.0_dp,TEMP))
  RCONST(279) = (ARR2(1.03D-12,-211.0_dp,TEMP))
  RCONST(280) = (ARR2(6.90D-13,-460.0_dp,TEMP))
  RCONST(281) = (ARR2(5.59D-13,-522.0_dp,TEMP))
  RCONST(282) = (ARR2(2.47D-13,-683.0_dp,TEMP))
  RCONST(283) = (ARR2(9.48D-13,-765.0_dp,TEMP))
  RCONST(284) = (ARR2(8.11D-13,-765.0_dp,TEMP))
  RCONST(285) = (ARR2(5.09D-13,-765.0_dp,TEMP))
  RCONST(286) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(287) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(288) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(289) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(290) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(291) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(292) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(293) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(294) = (ARR2(8.40D-14,-221.0_dp,TEMP))
  RCONST(295) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(296) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(297) = (ARR2(2.50D-12,-500.0_dp,TEMP))
  RCONST(298) = (ARR2(2.50D-12,-500.0_dp,TEMP))
  RCONST(299) = (ARR2(7.51D-13,-565.0_dp,TEMP))
  RCONST(300) = (ARR2(7.51D-13,-565.0_dp,TEMP))
  RCONST(301) = (ARR2(7.51D-13,-565.0_dp,TEMP))
  RCONST(302) = (ARR2(2.9D-12,-500.0_dp,TEMP))
  RCONST(303) = (ARR2(1.7D-12,-500.0_dp,TEMP))
  RCONST(304) = (ARR2(1.68D-12,-500.0_dp,TEMP))
  RCONST(305) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(306) = (ARR2(7.40D-13,-765.0_dp,TEMP))
  RCONST(307) = (ARR2(7.40D-13,-708.0_dp,TEMP))
  RCONST(308) = (ARR2(7.40D-13,-708.0_dp,TEMP))
  RCONST(309) = (ARR2(7.51D-13,-565.0_dp,TEMP))
  RCONST(310) = (ARR2(8.85D-13,-765.0_dp,TEMP))
  RCONST(311) = (ARR2(5.37D-13,-765.0_dp,TEMP))
  RCONST(312) = (ARR2(7.40D-13,-708.0_dp,TEMP))
  RCONST(313) = (ARR2(3.40D-14,-1560.0_dp,TEMP))
  RCONST(314) = (1.20D-12)
  RCONST(315) = (1.20D-12)
  RCONST(316) = (1.20D-12)
  RCONST(317) = (1.20D-12)
  RCONST(318) = (1.20D-12)
  RCONST(319) = (1.20D-12)
  RCONST(320) = (1.20D-12)
  RCONST(321) = (1.20D-12)
  RCONST(322) = (1.20D-12)
  RCONST(323) = (1.20D-12)
  RCONST(324) = (1.20D-12)
  RCONST(325) = (1.20D-12)
  RCONST(326) = (1.20D-12)
  RCONST(327) = (1.20D-12)
  RCONST(328) = (1.20D-12)
  RCONST(329) = (1.20D-12)
  RCONST(330) = (1.20D-12)
  RCONST(331) = (1.20D-12)
  RCONST(332) = (1.20D-12)
  RCONST(333) = (4.00D-12)
  RCONST(334) = (4.00D-12)
  RCONST(335) = (1.20D-12)
  RCONST(336) = (1.20D-12)
  RCONST(337) = (1.20D-12)
  RCONST(338) = (4.0D-12)
  RCONST(339) = (2.3D-12)
  RCONST(340) = (2.50D-12)
  RCONST(341) = (2.50D-12)
  RCONST(342) = (2.50D-12)
  RCONST(343) = (1.20D-12)
  RCONST(344) = (1.20D-12)
  RCONST(345) = (1.20D-12)
  RCONST(346) = (1.20D-12)
  RCONST(347) = (1.20D-12)
  RCONST(348) = (1.20D-12)
  RCONST(349) = (1.20D-12)
  RCONST(350) = (ARR2(2.50D-12,-500.0_dp,TEMP))
  RCONST(351) = (ARR2(2.50D-12,-500.0_dp,TEMP))
  RCONST(352) = (ARR2(7.00D-14,-1000.0_dp,TEMP))
  RCONST(353) = (ARR2(4.25D-14,-1000.0_dp,TEMP))
  RCONST(354) = (ARR2(2.96D-14,-1000.0_dp,TEMP))
  RCONST(355) = (ARR2(7.13D-17,-2950.0_dp,TEMP))
  RCONST(356) = (ARR2(4.12D8,7700.0_dp,TEMP))
  RCONST(357) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(358) = (ARR2(1.8D-13,-1300.0_dp,TEMP))
  RCONST(359) = (2.04D-13)
  RCONST(360) = (ARR2(2.58D-13,-500.0_dp,TEMP))
  RCONST(361) = (2.3D-12)
  RCONST(362) = (ARR2(1.6D-12,305.0_dp,TEMP))
  RCONST(363) = (1.0D-11)
  RCONST(364) = (ARR2(1.4D-12,1860.0_dp,TEMP))
  RCONST(365) = (5.0D-11)
  RCONST(366) = (5.6D-12)
  RCONST(367) = (ARR2(1.2D-11,-652.0_dp,TEMP))
  RCONST(368) = (ARR2(2.4D-12,-360.0_dp,TEMP))
  RCONST(369) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(370) = (6.7D-13)
  RCONST(371) = (ARR2(8.16D-13,-500.0_dp,TEMP))
  RCONST(372) = (2.3D-12)
  RCONST(373) = (ARR2(2.4D-12,-360.0_dp,TEMP))
  RCONST(374) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(375) = (7.5D-14)
  RCONST(376) = (ARR2(9.53D-14,-500.0_dp,TEMP))
  RCONST(377) = (2.3D-12)
  RCONST(378) = (1.1D-11)
  RCONST(379) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(380) = (ARR2(7.5D-12,-290.0_dp,TEMP))
  RCONST(381) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(382) = (ARR2(5.2D-13,-980.0_dp,TEMP))
  RCONST(383) = (8.24D-14)
  RCONST(384) = (ARR2(8.83D-13,-500.0_dp,TEMP))
  RCONST(385) = (ARR2(1.04D-13,-500.0_dp,TEMP))
  RCONST(386) = (ARR2(2.9D-12,-500.0_dp,TEMP))
  RCONST(387) = (2.3D-12)
  RCONST(388) = (4.0D-12)
  RCONST(389) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(390) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(391) = (4.6D-13)
  RCONST(392) = (ARR2(5.8D-13,-500.0_dp,TEMP))
  RCONST(393) = (2.3D-12)
  RCONST(394) = (1.0D-12)
  RCONST(395) = (1.0D-11)
  RCONST(396) = (j(Pj_onitOH1))
  RCONST(397) = (ARR2(2.4D-12,-745.00_dp,TEMP))
  RCONST(398) = (8.0D-13)
  RCONST(399) = (3.0D-12)
  RCONST(400) = (8.0D-12)
  RCONST(401) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(402) = (3.55D-12)
  RCONST(403) = (ARR2(4.23D-12,-500.0_dp,TEMP))
  RCONST(404) = (2.3D-12)
  RCONST(405) = (1.0D-11)
  RCONST(406) = (ARR2(6.13D-12,-200.0_dp,TEMP))
  RCONST(407) = (ARR2(3.73D-11,400.0_dp,TEMP))
  RCONST(408) = (ARR2(7.4D-13,-700.0_dp,TEMP))
  RCONST(409) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(410) = (2.3D-12)
  RCONST(411) = (ARR2(3.8D-12,-200.0_dp,TEMP))
  RCONST(412) = (ARR2(1.67D-11,-200.0_dp,TEMP))
  RCONST(413) = (ARR2(2.7D-11,-200.0_dp,TEMP))
  RCONST(414) = (4.0D-17)
  RCONST(415) = (2.0D-17)
  RCONST(416) = (ARR2(5.04D-14,1800.0_dp,TEMP))
  RCONST(417) = (ARR2(9.03D-16,845.0_dp,TEMP))
  RCONST(418) = (j(Pj_hpald))
  RCONST(419) = (j(Pj_ch3coch3))
  RCONST(420) = (j(Pj_glyc))
  RCONST(421) = (j(Pj_ch3o2h))
  RCONST(422) = (j(Pj_noa))
  RCONST(423) = (10*j(Pj_noa))
  RCONST(424) = (10*j(Pj_ibutald))
  RCONST(425) = (j(Pj_noa))
  RCONST(426) = (j(Pj_ch3cocho))
  RCONST(427) = (j(Pj_ch3o2h))
  RCONST(428) = (j(Pj_macr))
  RCONST(429) = (j(Pj_macr))
  RCONST(430) = (j(Pj_ch3o2h))
  RCONST(431) = (j(Pj_ch3o2h))
  RCONST(432) = (j(Pj_ch3o2h))
  RCONST(433) = (j(Pj_onitOH3))
  RCONST(434) = (j(Pj_onit1))
  RCONST(435) = (j(Pj_ald))
  RCONST(436) = (j(Pj_onitOH1))
  RCONST(437) = (j(Pj_onitOH1))
  RCONST(438) = (j(Pj_onitOH3))
  RCONST(439) = (j(Pj_onitOH3))
  RCONST(440) = (j(Pj_onitOH3))
  RCONST(441) = (4.00D-12)
  RCONST(442) = (4.00D-12)
  RCONST(443) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(444) = (ARR2(1.66D-13,-1300.0_dp,TEMP))
  RCONST(445) = (ARR2(1.60D-13,-708.0_dp,TEMP))
  RCONST(446) = (ARR2(9.68D-14,-708.0_dp,TEMP))
  RCONST(447) = (ARR2(8.85D-13,-765.0_dp,TEMP))
  RCONST(448) = (ARR2(5.37D-13,-765.0_dp,TEMP))
  RCONST(449) = (1.20D-12)
  RCONST(450) = (1.20D-12)
  RCONST(451) = (ARR2(7.00D-14,-1000.0_dp,TEMP))
  RCONST(452) = (ARR2(4.25D-14,-1000.0_dp,TEMP))
  RCONST(453) = (ARR2(2.96D-14,-1000.0_dp,TEMP))
  RCONST(454) = (ARR2(2.96D-14,-1000.0_dp,TEMP))
  RCONST(455) = (ARR2(4.25D-14,-1000.0_dp,TEMP))
  RCONST(456) = (ARR2(4.25D-14,-1000.0_dp,TEMP))
  RCONST(457) = (ARR2(7.00D-14,-1000.0_dp,TEMP))
  RCONST(458) = (1.79D-12)
  RCONST(459) = (7.3D-11)
  RCONST(460) = (4.8D-12)
  RCONST(461) = (4.1D-11)
  RCONST(462) = (7.29D-11)
  RCONST(463) = (1.67D-16)
  RCONST(464) = (7.2D-12)
  RCONST(465) = (ARR2(5.95D-12,1860.0_dp,TEMP))
  RCONST(466) = (k46(TEMP,C_M))
  RCONST(467) = (j(Pj_onitOH3))
  RCONST(468) = (8.1D-15)
  RCONST(469) = (4.00D-12)
  RCONST(470) = (2.30D-12)
  RCONST(471) = (5.2D-12)
  RCONST(472) = (ARR2(2.5D-14,300.0_dp,TEMP))
  RCONST(473) = (1.1D-10)
  RCONST(474) = (ARR2(2.7D-12,-360.0_dp,TEMP))
  RCONST(475) = (ARR2(2.06D-13,-1300.0_dp,TEMP))
  RCONST(476) = (6.9D-12)
  RCONST(477) = (6.9D-12)
  RCONST(478) = (1.1D-10)
  RCONST(479) = (4.2D-11)
  RCONST(480) = (2.3D-12)
  RCONST(481) = (2.3D-12)
  RCONST(482) = (8.4D-12)
  RCONST(483) = (1.25D-11)
  RCONST(484) = (5.0D-15)
  RCONST(485) = (5.0D-15)
  RCONST(486) = (1.1D-10)
  RCONST(487) = (4.2D-11)
  RCONST(488) = (2.3D-12)
  RCONST(489) = (2.3D-12)
  RCONST(490) = (1.7D-11)
  RCONST(491) = (1.7D-11)
  RCONST(492) = (ARR2(2.9D+7,5297.0_dp,TEMP))
  RCONST(493) = (ARR2(4.14D-12,-200.0_dp,TEMP))
  RCONST(494) = (ARR2(5.11D-12,-200.0_dp,TEMP))
  RCONST(495) = (ARR2(2.97D-11,-390.0_dp,TEMP))
  RCONST(496) = (ARR2(2.92D-11,-390.0_dp,TEMP))
  RCONST(497) = (ARR2(5.79D-11,400.0_dp,TEMP))
  RCONST(498) = (ARR2(3.20D-11,400.0_dp,TEMP))
! RCONST(499) = constant rate coefficient
! RCONST(500) = constant rate coefficient
! RCONST(501) = constant rate coefficient
! RCONST(502) = constant rate coefficient
! RCONST(503) = constant rate coefficient
! RCONST(504) = constant rate coefficient
! RCONST(505) = constant rate coefficient
! RCONST(506) = constant rate coefficient
! RCONST(507) = constant rate coefficient
! RCONST(508) = constant rate coefficient
! RCONST(509) = constant rate coefficient
! RCONST(510) = constant rate coefficient
! RCONST(511) = constant rate coefficient
! RCONST(512) = constant rate coefficient
! RCONST(513) = constant rate coefficient
! RCONST(514) = constant rate coefficient
! RCONST(515) = constant rate coefficient
! RCONST(516) = constant rate coefficient
! RCONST(517) = constant rate coefficient
! RCONST(518) = constant rate coefficient
! RCONST(519) = constant rate coefficient
! RCONST(520) = constant rate coefficient
! RCONST(521) = constant rate coefficient
! RCONST(522) = constant rate coefficient
! RCONST(523) = constant rate coefficient
! RCONST(524) = constant rate coefficient
! RCONST(525) = constant rate coefficient
! RCONST(526) = constant rate coefficient
! RCONST(527) = constant rate coefficient
! RCONST(528) = constant rate coefficient
! RCONST(529) = constant rate coefficient
! RCONST(530) = constant rate coefficient
! RCONST(531) = constant rate coefficient
! RCONST(532) = constant rate coefficient
! RCONST(533) = constant rate coefficient
! RCONST(534) = constant rate coefficient
! RCONST(535) = constant rate coefficient
! RCONST(536) = constant rate coefficient
! RCONST(537) = constant rate coefficient
! RCONST(538) = constant rate coefficient
! RCONST(539) = constant rate coefficient
! RCONST(540) = constant rate coefficient
! RCONST(541) = constant rate coefficient
! RCONST(542) = constant rate coefficient
! RCONST(543) = constant rate coefficient
! RCONST(544) = constant rate coefficient
! RCONST(545) = constant rate coefficient
! RCONST(546) = constant rate coefficient
! RCONST(547) = constant rate coefficient
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE r2smh_Global

  RCONST(1) = (j(Pj_o33p))
  RCONST(2) = (j(Pj_o31d))
  RCONST(3) = (j(Pj_h2o2))
  RCONST(4) = (j(Pj_no2))
  RCONST(5) = (j(Pj_no3o2))
  RCONST(6) = (j(Pj_no3o))
  RCONST(7) = (j(Pj_hno2))
  RCONST(8) = (j(Pj_hno3))
  RCONST(9) = (j(Pj_hno4))
  RCONST(10) = (j(Pj_ch2om))
  RCONST(11) = (j(Pj_ch2or))
  RCONST(12) = (j(Pj_ch3cho))
  RCONST(13) = (j(Pj_ald))
  RCONST(14) = (j(Pj_ch3coch3))
  RCONST(15) = (j(Pj_uald))
  RCONST(16) = (j(Pj_ch3coc2h5))
  RCONST(17) = (j(Pj_ch3coc2h5))
  RCONST(18) = (j(Pj_ch3coc2h5))
  RCONST(19) = (j(Pj_macr))
  RCONST(20) = (j(Pj_mvk))
  RCONST(21) = (j(Pj_hcocho))
  RCONST(22) = (j(Pj_hcochob))
  RCONST(23) = (j(Pj_hcochoc))
  RCONST(24) = (j(Pj_ch3cocho))
  RCONST(25) = (j(Pj_ch3cocho))
  RCONST(26) = (j(Pj_ch3cocho))
  RCONST(27) = (j(Pj_bald))
  RCONST(28) = (j(Pj_ch3o2h))
  RCONST(29) = (j(Pj_ch3o2h))
  RCONST(30) = (j(Pj_ch3coo2h))
  RCONST(31) = (j(Pj_iprno3))
  RCONST(32) = (j(Pj_pana))
  RCONST(33) = (j(Pj_panb))
  RCONST(396) = (j(Pj_onitOH1))
  RCONST(418) = (j(Pj_hpald))
  RCONST(419) = (j(Pj_ch3coch3))
  RCONST(420) = (j(Pj_glyc))
  RCONST(421) = (j(Pj_ch3o2h))
  RCONST(422) = (j(Pj_noa))
  RCONST(423) = (10*j(Pj_noa))
  RCONST(424) = (10*j(Pj_ibutald))
  RCONST(425) = (j(Pj_noa))
  RCONST(426) = (j(Pj_ch3cocho))
  RCONST(427) = (j(Pj_ch3o2h))
  RCONST(428) = (j(Pj_macr))
  RCONST(429) = (j(Pj_macr))
  RCONST(430) = (j(Pj_ch3o2h))
  RCONST(431) = (j(Pj_ch3o2h))
  RCONST(432) = (j(Pj_ch3o2h))
  RCONST(433) = (j(Pj_onitOH3))
  RCONST(434) = (j(Pj_onit1))
  RCONST(435) = (j(Pj_ald))
  RCONST(436) = (j(Pj_onitOH1))
  RCONST(437) = (j(Pj_onitOH1))
  RCONST(438) = (j(Pj_onitOH3))
  RCONST(439) = (j(Pj_onitOH3))
  RCONST(440) = (j(Pj_onitOH3))
  RCONST(467) = (j(Pj_onitOH3))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE r2smh_Rates

